# Generated by Django 3.0.2 on 2020-02-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='carousel_image/')),
            ],
            options={
                'verbose_name': 'Картинка для карусели',
                'verbose_name_plural': 'Картинки для карусели',
            },
        ),
        migrations.CreateModel(
            name='RightPictureSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_image', models.ImageField(upload_to='side_image/')),
            ],
            options={
                'verbose_name': 'Правая боковая картинка',
                'verbose_name_plural': 'Правые боковые картинки',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('title', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Описание питомника',
            },
        ),
    ]
