# Generated by Django 3.0.2 on 2020-02-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftPictureSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_image', models.ImageField(upload_to='side_image/')),
                ('small_left_picture', models.ImageField(upload_to='side_image/')),
            ],
            options={
                'verbose_name': 'Левая боковая картинка',
                'verbose_name_plural': 'Левые боковые картинки',
            },
        ),
    ]
