# Generated by Django 3.0.2 on 2020-01-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0002_picturecarousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picturecarousel',
            options={'verbose_name': 'Картинка для карусели', 'verbose_name_plural': 'Картинки для карусели'},
        ),
    ]
