# Generated by Django 3.0.2 on 2020-01-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0003_auto_20200117_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='side_image/')),
            ],
            options={
                'verbose_name': 'Боковая картинка',
                'verbose_name_plural': 'Боковые картинки',
            },
        ),
    ]
