# Generated by Django 3.0.2 on 2020-02-01 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0004_leftpictureside_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftpictureside',
            name='picture',
        ),
    ]
