# Generated by Django 3.0.2 on 2020-01-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0004_pictureside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureside',
            old_name='image',
            new_name='left_image',
        ),
        migrations.AddField(
            model_name='pictureside',
            name='right_image',
            field=models.ImageField(default=0, upload_to='side_image/'),
            preserve_default=False,
        ),
    ]
