# Generated by Django 3.0.2 on 2020-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0005_auto_20200122_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftPictureSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_image', models.ImageField(upload_to='side_image/')),
            ],
            options={
                'verbose_name': 'Левая боковая картинка',
                'verbose_name_plural': 'Левые боковые картинки',
            },
        ),
        migrations.CreateModel(
            name='RightPictureSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_image', models.ImageField(upload_to='side_image/')),
            ],
            options={
                'verbose_name': 'Правая боковая картинка',
                'verbose_name_plural': 'Правые боковые картинки',
            },
        ),
        migrations.DeleteModel(
            name='PictureSide',
        ),
    ]
