# Generated by Django 3.0.2 on 2020-01-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
