# Generated by Django 3.0.2 on 2020-01-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20200114_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(height_field=100, upload_to='animals_image/', width_field=100),
        ),
    ]
