# Generated by Django 3.0.2 on 2020-01-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20200115_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='animals_image/'),
        ),
    ]
