# Generated by Django 3.0.2 on 2020-01-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20200115_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='picture',
            field=models.ImageField(default=0, upload_to='animals_image/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
