# Generated by Django 3.0.2 on 2020-01-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20200115_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='our_animals/')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Наши щенки',
                'verbose_name_plural': 'Наш щенок',
            },
        ),
    ]
