# Generated by Django 3.0.2 on 2020-01-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_ouranimal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ouranimal',
            options={'verbose_name': 'Наш щенок', 'verbose_name_plural': 'Наши щенки'},
        ),
    ]
