# Generated by Django 3.0.2 on 2020-02-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_auto_20200128_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouranimal',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
